endpoint: '127.0.0.1:9000'
options:
  secure: false
  credentials:
    access_key: 'admin'
    secret_key: 'lark2022'
    token: ''
bucket:
  bucket_names: ["documents","photos","videos"]
  make_bucket_options:
    region: 'cn-gz'
    objectLocking: false
  put_object_options:
    encrypted: false
